baseURL = "https://hugo-restructured-demo.netlify.com/"
languageCode = "en-us"
title = "Example.org"

SectionPagesMenu = "main"

theme = "hugo-restructured"

[params]
   #author = "William Shakespeare"

   # Adapt the two lines below to use local images
   hero_image = "/img/typography-725149_1920.jpg"
   hero_color = "gray90"

   # Alternative: Red gradients for pages
   #hero_color = "white"
   #hero_shade = "background: #870000; background: linear-gradient(to right, #190a05, #870000);" # https://uigradients.com/#TheStrain

   #edge_shade = "background: #fdfcfb; background: linear-gradient(to bottom, #fdfcfb, #e2d1c3);" # https://webgradients.com -- 029 Everlasting Sky

